#!/bin/sh
set -e

export PATH="/usr/sbin:/sbin:$PATH"

rm -f /home/sasogu/ISO/debian-live/config/includes.chroot_before_packages/etc/aulalliure/minimal-build

/home/sasogu/ISO/debian-live/auto/config-full
lb clean --purge
lb build noauto
