#!/bin/sh
set -e

export PATH="/usr/sbin:/sbin:$PATH"

ROOT="${HOME}/ISO/debian-live"

rm -f "${ROOT}/config/includes.chroot_before_packages/etc/aulalliure/minimal-build"

if [ -f "${ROOT}/config/package-lists/moksha.list.chroot.disabled" ]; then
	mv "${ROOT}/config/package-lists/moksha.list.chroot.disabled" "${ROOT}/config/package-lists/moksha.list.chroot"
fi

lb clean --purge
"${ROOT}/auto/config-full"
lb build noauto
