#!/bin/sh
set -e

lb config noauto \
  --mode debian \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer live \
  --debian-installer-gui false \
  --debian-installer-preseedfile preseed/auto.cfg \
  --bootappend-live "boot=live components auto=true priority=critical preseed/file=/cdrom/preseed/auto.cfg" \
  --iso-application "Debian 13 Moksha" \
  --iso-publisher "Custom" \
  --iso-volume "DEBIAN13_MOKSHA" \
  --memtest none
